/**
 * Public order references.
 *
 * `Order.orderNumber` is a PostgreSQL sequence-backed integer, generated by the
 * database as a column DEFAULT (`nextval('order_number_seq')`). It is entirely
 * separate from `Order.id`, which is a cuid and is never exposed.
 *
 * Why a sequence:
 *
 *   - It is concurrency-safe. `nextval` never hands the same value to two
 *     sessions, and it does not depend on reading existing rows. `COUNT(*) + 1`
 *     and `MAX(...) + 1` both race under concurrent checkout and would issue
 *     duplicate order numbers.
 *   - It cannot be forgotten. Because it is a column default rather than
 *     application code, an order created by a script, a test, or a future code
 *     path still gets a valid number.
 *   - It is not the primary key, so the public reference and the internal
 *     identifier can diverge without a data migration.
 *
 * Known tradeoff, accepted for MVP: a monotonic sequence leaks order volume to
 * anyone who places two orders. Increasing the sequence increment, or changing
 * the display format below, addresses that later without touching stored data.
 *
 * The DISPLAY format lives here and nowhere else, which is what keeps it
 * changeable. Nothing persists a formatted string.
 */

/** Where `order_number_seq` starts, so the first order is not "order 1". */
export const FIRST_ORDER_NUMBER = 100001;

/** Where `custom_request_number_seq` starts, in its own number space. */
export const FIRST_CUSTOM_REQUEST_NUMBER = 500001;

/**
 * Render an order number for a customer: `100001`.
 *
 * Deliberately plain. A prefix or a date segment can be added here later — the
 * stored integer is the identity, the string is presentation.
 */
export function formatOrderNumber(orderNumber: number): string {
  assertPublicNumber(orderNumber, 'order number');
  return String(orderNumber);
}

/** Render a custom-request number: `500001`. */
export function formatCustomRequestNumber(requestNumber: number): string {
  assertPublicNumber(requestNumber, 'custom request number');
  return String(requestNumber);
}

/**
 * Parse a customer-supplied reference — an order-lookup form, a support email.
 *
 * Returns `null` rather than throwing, because the input is untrusted: a
 * customer typing a wrong reference is an expected case, not an exception.
 */
export function parseOrderNumber(input: string): number | null {
  const trimmed = input.trim();
  if (!/^\d{1,9}$/.test(trimmed)) return null;

  const value = Number(trimmed);
  return value >= FIRST_ORDER_NUMBER ? value : null;
}

function assertPublicNumber(value: number, label: string): void {
  if (!Number.isInteger(value) || value <= 0) {
    throw new RangeError(
      `Invalid ${label}: ${value}. Expected a positive integer from the sequence.`,
    );
  }
}
